# Generated by Django 5.0.7 on 2025-08-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_admininvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininvite',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('instructor', 'Instructor'), ('user', 'User')], default='user', help_text='Role assigned to the invited account', max_length=32),
        ),
    ]
