# Generated by Django 5.0.7 on 2025-08-08 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('code', 'Code'), ('video', 'Video'), ('prompt', 'Interactive Prompt')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='courses.lesson')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
