# Generated by Django 5.0.7 on 2025-08-08 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_prompttemplatecategory_prompttemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePromptCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_collections', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course_id', 'order', 'title', 'id'],
                'unique_together': {('course', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CoursePromptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional display title; defaults to template title', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('content_override', models.TextField(blank=True, help_text='Optional content to override the template content')),
                ('variables_override', models.JSONField(blank=True, default=list)),
                ('params_override', models.JSONField(blank=True, default=dict)),
                ('tags_override', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='courses.coursepromptcollection')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_items', to='courses.prompttemplate')),
            ],
            options={
                'ordering': ['collection_id', 'order', 'id'],
                'indexes': [models.Index(fields=['collection', 'order'], name='courses_cou_collect_260be3_idx')],
                'unique_together': {('collection', 'slug')},
            },
        ),
    ]
