# Generated by Django 5.0.7 on 2025-08-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_coursepromptcollection_coursepromptitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='attempts_allowed',
            field=models.PositiveIntegerField(default=1, help_text='Number of attempts allowed, 0 for unlimited'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions shown to students before taking the quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='randomize_questions',
            field=models.BooleanField(default=False, help_text='Randomize question order for each attempt'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_results_immediately',
            field=models.BooleanField(default=True, help_text='Show results immediately after submission'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Time limit in minutes, null for no limit', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation shown after answering (optional)'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Whether this question must be answered'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='points',
            field=models.PositiveIntegerField(default=1, help_text='Points awarded for correct answer'),
        ),
    ]
