# Generated by Django 5.0.7 on 2025-08-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_quiz_attempts_allowed_quiz_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='attempts_allowed',
            field=models.PositiveIntegerField(blank=True, help_text='Number of attempts allowed, 0 for unlimited', null=True),
        ),
    ]
