name: Backend CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements.txt

      - name: Django system check
        env:
          DJANGO_DEV: '1'
        run: |
          python backend/manage.py check

      - name: Run migrations (SQLite dev)
        env:
          DJANGO_DEV: '1'
        run: |
          python backend/manage.py migrate --noinput
